apiVersion: v1
kind: Pod
metadata:
  name: dotnet-dev  
spec:
  containers:
    - name: dev
      image: mcr.microsoft.com/devcontainers/dotnet:1-9.0-bookworm
      command: ["sleep", "infinity"]
      tty: true
      stdin: true
      volumeMounts:
        - mountPath: /workspace
          name: code
  volumes:
  - name: code
    emptyDir: {}