apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockube-code-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/Repos/Github/Dockube"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockube-code-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aspnet-cert-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/Users/harri/.aspnet/https"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aspnet-cert-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
