apiVersion: v1
kind: Pod
metadata:
  name: dotnet-dev
  labels:
    app: devcontainer
spec:
  containers:
    - name: dev
      image: mcr.microsoft.com/devcontainers/dotnet:1-9.0-bookworm
      command: ["sleep", "infinity"]
      tty: true
      stdin: true
      env:
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/workspace/test/certifikat/dockubeapi.dockube.lan.pfx"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "myPazzw0rd"
      volumeMounts:
        - name: code
          mountPath: /workspace
  volumes:
    - name: code
      persistentVolumeClaim:
        claimName: dockube-code-pvc
