apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dockube
spec:
  destination:
    namespace: 
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ##RepositoryUrl##
    path: ##RepositoryPath##
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true