name: Grafana
namespace: observation
isCore: true
resources:
  - type: kubectl
    source: Grafana.yaml
    endpoint: https://grafana.$$DOMAIN_NAME$$
    certificates:
      - subjectCn: grafana
        keyUsage: serverAuth          
    after:
      - $SLEEP$      
      - kubectl get pods -n observation
