adminUser: admin
adminPassword: dockube123

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: false  # Docker Desktop stödjer sällan PVCs utan vidare

rbac:
  create: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server  # Ändra om du använder annan tjänst
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus

env:
  GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "false"
  GF_USERS_ALLOW_SIGN_UP: "false"
