/*
 * DockubeTemplate
 *
 * This is a service contract for the Dockube API.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using DockCubeApi.Server.Attributes;
using DockCubeApi.Server.Models;

namespace DockCubeApi.Server.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ClusterApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Get pods or specific pod</remarks>
        /// <param name="podName">The preferred name of the repository</param>
        /// <response code="200">Success</response>
        /// <response code="400">Error response for 400</response>
        [HttpGet]
        [Route("/api/v1/cluster")]
        [ValidateModelState]
        [SwaggerOperation("Get")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Pod>), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(Problem), description: "Error response for 400")]
        public abstract IActionResult Get([FromQuery (Name = "podName")]string? podName);
    }
}
