services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    restart: unless-stopped
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC
      - "9997:9997"   # Universal Forwarder
      - "8089:8089"   # Management API (för CLI och automation)
    environment:
      - SPLUNK_PASSWORD=*****
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=Free
    volumes:
      - splunk-data:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc

volumes:
  splunk-data:
  splunk-etc: 
