apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockube-dotnetui-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/run/desktop/mnt/host/c/Repos/Github/Dockube"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockube-dotnetui-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi