apiVersion: v1
kind: Pod
metadata:
  name: dotnet-dev
  labels:
    app: devcontainer-dotnet-ui
spec:
  containers:
    - name: dev
      image: mcr.microsoft.com/devcontainers/dotnet:1-9.0-bookworm
      command: ["sleep", "infinity"]
      tty: true
      stdin: true
      env:
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/workspace/test/certifikat/ui.dockube.lan.pfx"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: <ENCRYPTED_STRING>EAAAALPTeg8+xzXxYcK4I2X4eDSH8F9hpxUdoSI+5Oq+FgHo</ENCRYPTED_STRING>
        - name: DOCKUBE__GITLAB__TOKEN
          value: <ENCRYPTED_STRING>EAAAAO2TywXrWgjNAzh0zclnmBxDhcR6ykij/wgwqyv0S/b2HQfU5bs+6QMLHquOSayFPQ==</ENCRYPTED_STRING>
      volumeMounts:
        - name: code
          mountPath: /workspace
  volumes:
    - name: code
      persistentVolumeClaim:
        claimName: dockube-dotnetui-pvc
