apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dockube-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.150-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dockube-advert
  namespace: metallb-system