apiVersion: v1
kind: Service
metadata:
  name: gogs-svc
  namespace: gogs
spec:
  type: NodePort
  selector:
    app: gogs
  ports:
  - name: ssh
    protocol: TCP
    port: 10022
    targetPort: 22
    nodePort: 30022
  - name: http
    protocol: TCP
    port: 18080
    targetPort: 3000
    nodePort: 30080