openapi: 3.0.2
info:
  title: DockubeTemplate
  version: '2.0'
  description: This is a service contract for the Dockube API.

servers:
  - url: http://localhost/api/v1

tags:
  - name: Cluster
    description: Cluster methods

paths:
  /cluster:
    get:
      tags:
        - Cluster
      operationId: Get
      description: Get pods or specific pod
      parameters:
        - name: podName
          in: query
          description: The preferred name of the repository
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pod'
              example:
                - name: argocd
                  status: running
        '400':
          $ref: '#/components/responses/ErrorResponse400'

components:
  schemas:
    Pod:
      type: object
      properties:
        name:
          type: string
          description: The metadata name of the pod
        phase:
          type: string
          description: The current status of the pod
        kind:
          type: string
          description: The kubernetes kind
        uid:
          type: string
          description: The uniquee identifier.
    Problem:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://zalando.github.io/problem/constraint-violation
        title:
          type: string
          description: |
            A short summary of the problem type. Written in English and readable
            for engineers (usually not suited for non-technical stakeholders and
            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human-readable explanation specific to this occurrence of the
            problem.
          example: Connection to the database timed out
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.

  responses:
    ErrorResponse400NoRepo:
      description: Error response for 400
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            title: Bad Request
            status: 400
            detail: No such repository

    ErrorResponse400:
      description: Error response for 400
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            title: Bad Request
            status: 400
            detail: Generic error
