@PainKiller.DockubeAPI_HostAddress = http://localhost:5273

GET {{PainKiller.DockubeAPI_HostAddress}}/todos/
Accept: application/json

###

GET {{PainKiller.DockubeAPI_HostAddress}}/todos/1
Accept: application/json

###
