name: ArgoCD
namespace: argocd
isCore: true
retries: 200
resources:  
  - type: kubectl
    source: ArgoCd.yaml    
    secretDescriptors:
      - name: ArgoCd login with admin/password
        key: argocd-initial-admin-secret
        showClearText: true
    certificates:
      - subjectCn: argocd
        keyUsage: serverAuth
  - type: kubectl
    source: ArgoCd-Ingress.yaml
    endpoint: https://argocd.$$DOMAIN_NAME$$    
    after:
      - $SLEEP$
      - kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o name       