version: 1.0
configuration:
  dockube:
    manifestBasePath: Manifests
    ssl:
      executablePath: OpenSSL-Win64\bin
      output: ssl-output
      defaultName: Dockube
      defaultCa: Dockube Intermediate CA
    ssh:
      host: dockube.local
      port: 22
      userName: dockube
    releases:
      - name: Grafana-Prometheus
        namespace: observation
        resources:
          - type: kubectl
            source: Grafana-Prometheus.yaml
            before:
              - echo Starting Prometheus and Grafana installation
            after:
              - echo Prometheus and Grafana services deployed
              - $ASYNC$ kubectl port-forward svc/grafana 3000:80 -n observation
              - kubectl get pods -n observation
              - kubectl create secret tls grafana-tls --cert=ssl-output\certificate\grafana.dockube.lan.pem --key=ssl-output\key\grafana.dockube.lan.key -n observation
              - kubectl create secret tls prometheus-tls --cert=ssl-output\certificate\prometheus.dockube.lan.pem --key=ssl-output\key\prometheus.dockube.lan.key -n observation
              - echo Access Grafana at https://grafana.dockube.lan

      - name: Grafana-Prometheus-Helm
        namespace: observation
        resources:
          - type: helm
            source: grafana
            before:
              - echo Installing Grafana using Helm chart
              - helm repo add grafana https://grafana.github.io/helm-charts
            after:
              - echo Grafana Helm chart deployed
              - $ASYNC$ kubectl port-forward svc/grafana 3000:80 -n observation
              - kubectl get pods -n observation
            parameters:
              repo: https://grafana.github.io/helm-charts
              version: 7.3.0
              values: grafana-values.yaml
      - name: Ingress-Nginx-Helm
        namespace: ingress-nginx
        resources:
         - type: helm
           source: ingress-nginx
           before:
             - echo Installing NGINX Ingress Controller using Helm chart
             - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
           after:
             - echo NGINX Ingress deployed
             - $SLEEP$
             - kubectl get svc -n ingress-nginx
           parameters:
             repo: https://kubernetes.github.io/ingress-nginx
             version: 4.12.3  
             values: ingress-values.yaml
  core:
    name: Dockube
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    logoColor: DarkMagenta
    suggestions:
      - exit
    roamingDirectory: Dockube
    modules:
      security:
        secrets:
          - name: CommandPrompt_encryptionManager
            options:
              target: User        
          - name: dockube_ssh
            options:
              target: User
      storage:
        applicationDataFolder: $ROAMING$\Dockube
        backupPath: backup
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
        backgroundColor: DarkMagenta
        foregroundColor: White
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug