version: 1.0
configuration:
  dockube:
    manifestBasePath: Manifests
    defaultDomain: dockube.lan
    ssl:
      executablePath: OpenSSL-Win64\bin
      output: ssl-output
      defaultName: Dockube
      defaultCa: Dockube Intermediate CA      
    ssh:
      - name: nas
        host: dockube.local
        port: 22
        userName: dockube
      - name: r1
        host: dockube.server
        port: 22
        userName: dockube
    releases:
      - Ingress-Nginx-Helm  
      - Prometheus      
      - Grafana
      - Mailpit
      - Gitlab
      - Minio
      - ArgoCd
      - KubernetesDashboard
  core:
    name: Dockube
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    logoColor: DarkMagenta
    suggestions:
      - exit
    roamingDirectory: Dockube
    modules:
      security:
        secrets:
          - name: CommandPrompt_encryptionManager
            options:
              target: User        
          - name: dockube_ssh_nas
            options:
              target: User
          - name: dockube_ssh_r1
            options:
              target: User
          - name: dockube-gitlab
            options:
              target: User
      storage:
        applicationDataFolder: $ROAMING$\Dockube
        backupPath: backup
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
        backgroundColor: DarkMagenta
        foregroundColor: White
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug