version: 1.0
configuration:
  dockube:
    manifestBasePath: Manifests
    ssl:
      executablePath: OpenSSL-Win64\bin
      output: ssl-output
      defaultName: Dockube
      defaultCa: Dockube Intermediate CA
    ssh:
      host: dockube.local
      port: 22
      userName: dockube
    releases:
      - name: Grafana-Prometheus
        namespace: observation
        resources:
          - type: kubectl
            source: Grafana-Prometheus.yaml
            before:
              - echo Starting Prometheus and Grafana installation
            after:
              - echo Prometheus and Grafana services deployed
              - $ASYNC$ kubectl port-forward svc/grafana 3000:80 -n observation
              - kubectl get pods -n observation

      - name: Grafana-Prometheus-Helm
        namespace: observation
        resources:
          - type: helm
            source: grafana
            before:
              - echo Installing Grafana via Helm
            after:
              - echo Grafana Helm chart deployed
              - $ASYNC$ kubectl port-forward svc/grafana 3000:80 -n observation
              - kubectl get pods -n observation
            parameters:
              repo: https://grafana.github.io/helm-charts
              version: 7.3.0
              values: grafana-values.yaml

  core:
    name: Dockube
    version: 1.0
    prompt: cp>
    defaultCommand: ''
    showLogo: true
    logoColor: DarkMagenta
    suggestions:
      - exit
    roamingDirectory: Dockube
    modules:
      security:
        secrets:
          - name: CommandPrompt_encryptionManager
            options:
              target: User        
          - name: dockube_ssh
            options:
              target: User
      storage:
        applicationDataFolder: $ROAMING$\Dockube
        backupPath: backup
      infoPanel:
        enabled: true
        height: 2
        updateIntervalSeconds: -1
        backgroundColor: DarkMagenta
        foregroundColor: White
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug