controller:
  publishService:
    enabled: true
  metrics:
    enabled: true
  admissionWebhooks:
    enabled: true
  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
  ingressClassResource:
    name: nginx
    enabled: true
    default: false
  ingressClass: nginx