name: Ingress-Nginx-Helm
namespace: ingress-nginx
isCore: true
order: 1
resources:
  - type: helm
    source: ingress-nginx
    before:
      - echo Installing NGINX Ingress Controller using Helm chart
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      - helm repo add gitlab https://charts.gitlab.io
      - helm repo update
    after:
      - echo NGINX Ingress deployed
      - $SLEEP$
      - kubectl get svc -n ingress-nginx
    parameters:
      repo: https://kubernetes.github.io/ingress-nginx
      version: 4.12.3
      values: ingress-values.yaml
