name: Prometheus
namespace: observation
isCore: true
resources:
  - type: kubectl
    source: Prometheus.yaml
    endpoint: https://prometheus.$$DOMAIN_NAME$$/targets
    certificates:      
      - subjectCn: prometheus
        keyUsage: serverAuth    
    after:      
      - $SLEEP$      
      - kubectl get pods -n observation
