version: 1.0
configuration:
  manifestBasePath: Manifests  
  gitlab:
    baseUrl: http://gitlab-webservice-default.gitlab.svc.cluster.local:8080
    repository: Dockube
    userName: dockube@dockube.lan
    accessToken: glpat-LC315rjp2Ff3dZde8LAj
  core:
    name: Dockube
    version: 1.0        
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug