version: 1.0
configuration:
  manifestBasePath: Manifests  
  gitlab:
    baseUrl: http://gitlab.gitlab.svc.cluster.local
    repository: Dockube
    userName: Dockube    
    email: dockube@dockube.lan    
  core:
    name: Dockube
    version: 1.0        
  log:
    fileName: commandprompt.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Debug