#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/DockCubeApi.Server/ && \
    dotnet build src/DockCubeApi.Server/ && \
    echo "Now, run the following to start the project: dotnet run -p src/DockCubeApi.Server/DockCubeApi.Server.csproj --launch-profile web"
